"""Winnougan Node Suite for ComfyUI"""

from .winnougan_prompt_encoder import (
    NODE_CLASS_MAPPINGS as PROMPT_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY,
)
from .winnougan_clip_loader import (
    NODE_CLASS_MAPPINGS as CLIP_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CLIP_DISPLAY,
)
from .winnougan_power_lora_loader import (
    NODE_CLASS_MAPPINGS as LORA_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_DISPLAY,
)
from .winnougan_resolution_picker import (
    NODE_CLASS_MAPPINGS as RES_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RES_DISPLAY,
)
from .Winnougan_LTX_Resolution_Picker import (
    NODE_CLASS_MAPPINGS as LTX_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LTX_DISPLAY,
)
from .winnougan_checkpoint_loader import (
    NODE_CLASS_MAPPINGS as CKPT_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CKPT_DISPLAY,
)

NODE_CLASS_MAPPINGS = {
    **PROMPT_MAPPINGS,
    **CLIP_MAPPINGS,
    **LORA_MAPPINGS,
    **RES_MAPPINGS,
    **LTX_MAPPINGS,
    **CKPT_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **PROMPT_DISPLAY,
    **CLIP_DISPLAY,
    **LORA_DISPLAY,
    **RES_DISPLAY,
    **LTX_DISPLAY,
    **CKPT_DISPLAY,
}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
